'use client';
import Link from 'next/link';
import '../marketing.css';
import MarketingNav from '../../components/MarketingNav';
import MarketingFooter from '../../components/MarketingFooter';

function Table({ headers, rows, widths }) {
  return (
    <div style={{ overflowX: 'auto', margin: '12px 0' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14, minWidth: 560 }}>
        <thead>
          <tr>{headers.map((h, i) => (
            <th key={i} style={{ textAlign: 'left', padding: '9px 12px', borderBottom: '2px solid var(--line, #e7e9f2)', background: 'rgba(108,92,231,.06)', width: widths ? widths[i] : undefined }}>{h}</th>
          ))}</tr>
        </thead>
        <tbody>
          {rows.map((r, ri) => (
            <tr key={ri}>{r.map((c, ci) => (
              <td key={ci} style={{ padding: '9px 12px', borderBottom: '1px solid var(--line-soft, #eef0f6)', verticalAlign: 'top' }}>{c}</td>
            ))}</tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function Privacy() {
  return (
    <div className="mk">
      <MarketingNav />
      <section className="mk-pagehero">
        <div className="mk-container">
          <div className="mk-kicker" style={{ color: 'var(--violet)', fontWeight: 700, letterSpacing: '.08em' }}>LEGAL</div>
          <h1 style={{ marginTop: 12 }}>Privacy Notice</h1>
          <p>How Reffolio collects and uses personal data. Last updated: [DATE] {'\u00b7'} Version 1.0</p>
        </div>
      </section>

      <section className="mk-section" style={{ paddingTop: 16 }}>
        <div className="mk-container" style={{ maxWidth: 820 }}>
          <div style={{ background: '#FFF7E6', borderLeft: '4px solid #E8A317', borderRadius: 8, padding: '12px 16px', marginBottom: 28, fontSize: 14 }}>
            This notice is being finalised. Some details shown in [brackets] are placeholders pending registration and legal review.
          </div>

          <h2>1. Who we are</h2>
          <p>This privacy notice explains how [LEGAL ENTITY NAME] (&ldquo;Reffolio&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;), company number [COMPANY NUMBER], registered at [REGISTERED ADDRESS], collects and uses personal data when you use the Reffolio platform at reffolio.co.uk and related services.</p>
          <p>For the platform and our own business operations, Reffolio is a data controller. When we process reference content on behalf of an employer or agency that issues or requests references through Reffolio, we generally act as a data processor on that organisation&rsquo;s behalf (see section 9).</p>
          <p>We are registered with the UK Information Commissioner&rsquo;s Office (ICO), registration number [ICO REGISTRATION NUMBER]. For any privacy question or to exercise your rights, contact [PRIVACY CONTACT EMAIL].</p>

          <h2>2. Who this notice covers</h2>
          <ul>
            <li>Workers &mdash; people who are the subject of references.</li>
            <li>Referees &mdash; people asked to provide or confirm a reference.</li>
            <li>Organisation users &mdash; staff at employers and agencies who request, issue or manage references.</li>
            <li>Website visitors &mdash; people who browse our public website.</li>
          </ul>

          <h2>3. The personal data we collect</h2>
          <Table
            headers={['Category', 'Examples', 'Source']}
            widths={['26%', '48%', '26%']}
            rows={[
              ['Account data', 'Name, email, role, organisation, job title, login identifiers', 'You / your organisation'],
              ['Worker identity & verification', 'Full name, professional registration body and number, DBS certificate number, a tamper-evident identity hash', 'You / your organisation'],
              ['Reference content', 'Employment dates, role, conduct, attendance, disciplinary and capability matters, safeguarding information, suitability assessments', 'The issuing or requesting organisation / referee'],
              ['Referee data', 'Name, job title, work email, confirmation status', 'The organisation'],
              ['Sharing & access data', 'Request and share links, verification codes, when a reference was opened and by whom', 'Generated by the platform'],
              ['Billing data', 'Plan, seats, payment status (card details handled by Stripe, not stored by us)', 'You / Stripe'],
              ['Technical data', 'IP address, device/browser information, usage logs', 'Automatically collected'],
            ]}
          />

          <h2>4. Special-category and criminal-offence data</h2>
          <p>References in regulated sectors can include information needing extra protection under UK data-protection law:</p>
          <ul>
            <li>Criminal-offence data (Article 10 UK GDPR / DPA 2018) &mdash; such as DBS details and information about safeguarding allegations or disciplinary matters.</li>
            <li>Potentially special-category data (Article 9) &mdash; where a reference incidentally reveals health or other protected information.</li>
          </ul>
          <p>We process this only where a condition in Schedule 1 of the Data Protection Act 2018 applies &mdash; in particular safeguarding of children and individuals at risk, and employment purposes &mdash; and we keep an appropriate policy document. [CONFIRM SCHEDULE 1 CONDITIONS WITH YOUR ADVISER]</p>

          <h2>5. How we use your data and our lawful bases</h2>
          <Table
            headers={['Purpose', 'Lawful basis']}
            widths={['58%', '42%']}
            rows={[
              ['Providing the platform and your account', 'Contract'],
              ['Verifying worker identity and registration', 'Legitimate interests; legal obligation where applicable'],
              ['Creating, requesting, assessing and storing references', 'Legitimate interests of the organisation; safeguarding'],
              ['Letting workers share references by consent', 'Consent for the share itself'],
              ['AI fairness and sector analysis of references', 'Legitimate interests'],
              ['Billing and fraud prevention', 'Contract; legal obligation'],
              ['Security, logging and service improvement', 'Legitimate interests'],
            ]}
          />

          <h2>6. Who we share data with</h2>
          <ul>
            <li>Recipients of a reference &mdash; the requesting organisation, and (in the worker-held model) anyone the worker chooses to share with after they verify their email.</li>
            <li>The organisation and its authorised users &mdash; for references they create, request or manage.</li>
            <li>Our service providers (processors) &mdash; listed in section 7.</li>
            <li>Authorities or advisers &mdash; where legally required, or to establish or defend legal claims.</li>
          </ul>
          <p>We do not sell personal data, and we do not use it for advertising.</p>

          <h2>7. Our processors and sub-processors</h2>
          <Table
            headers={['Provider', 'Purpose', 'Location']}
            widths={['24%', '50%', '26%']}
            rows={[
              ['Supabase', 'Database and authentication hosting', '[CONFIRM REGION]'],
              ['Railway', 'Backend application hosting', '[CONFIRM REGION]'],
              ['Vercel', 'Frontend website hosting', '[CONFIRM REGION]'],
              ['Resend', 'Transactional email delivery', '[CONFIRM REGION]'],
              ['Stripe', 'Payment processing', 'EU / US'],
              ['Anthropic', 'AI analysis of reference content', 'US'],
            ]}
          />

          <h2>8. International transfers</h2>
          <p>Some providers process data outside the UK, including in the United States. Where that happens, we rely on appropriate safeguards &mdash; such as the UK International Data Transfer Agreement or the UK Addendum to the EU Standard Contractual Clauses &mdash; together with the provider&rsquo;s own measures. [CONFIRM THE MECHANISM FOR EACH PROVIDER WITH YOUR ADVISER.]</p>

          <h2>9. Controller and processor roles</h2>
          <p>Reffolio is the controller for your account, billing, security and the operation of the platform. When an organisation requests or issues a reference through Reffolio, that organisation is the controller for the reference content and Reffolio acts as its processor under a data-processing agreement. [HAVE YOUR ADVISER CONFIRM THE ANALYSIS FOR THE WORKER-HELD MODEL.]</p>

          <h2>10. How long we keep data</h2>
          <ul>
            <li>Account data &mdash; while your account is active, then [RETENTION PERIOD] after closure.</li>
            <li>References and verification records &mdash; [RETENTION PERIOD], reflecting safeguarding and regulatory expectations.</li>
            <li>Billing records &mdash; as required by law (typically six years).</li>
            <li>Logs &mdash; [RETENTION PERIOD].</li>
          </ul>

          <h2>11. Your rights</h2>
          <p>Under UK data-protection law you have the right to access your data; to have it corrected or erased; to restrict or object to processing; to data portability; and to withdraw consent where we rely on it. To exercise any of these, contact [PRIVACY CONTACT EMAIL]; we will respond within one month. Where a reference about you was issued or requested by an organisation (Reffolio as processor), we may direct your request to that organisation as the controller and help you do so.</p>
          <p>You also have the right to complain to the ICO (ico.org.uk, helpline 0303 123 1113), though we hope you will contact us first.</p>

          <h2>12. Cookies</h2>
          <p>We use only the cookies and local storage needed to keep you signed in and the service secure. We do not use advertising or third-party tracking cookies.</p>

          <h2>13. Changes to this notice</h2>
          <p>We may update this notice from time to time. We will change the &ldquo;last updated&rdquo; date above and, for significant changes, tell you directly where appropriate.</p>

          <h2>14. Contact</h2>
          <p>[LEGAL ENTITY NAME], [REGISTERED ADDRESS]. Email: [PRIVACY CONTACT EMAIL]. ICO registration: [ICO REGISTRATION NUMBER].</p>
          <p style={{ marginTop: 20 }}>
            Our Data Processing Agreement for organisations is available on request &mdash;{' '}
            <a href="mailto:support@reffolio.co.uk?subject=DPA%20request">request a copy</a>.
          </p>

          <div className="mk-cta" style={{ marginTop: 44 }}>
            <h2>Questions about your data?</h2>
            <p>We&rsquo;re happy to help. Get in touch and we&rsquo;ll respond promptly.</p>
            <Link href="/contact" className="mk-btn mk-btn-primary mk-btn-lg">Contact us</Link>
          </div>
        </div>
      </section>

      <MarketingFooter />
    </div>
  );
}
