-- ============================================================
-- 0018  Hybrid reference forms (field_schema update)
--   * care: designed from real CQC-sector samples
--   * healthcare / teaching / social_work: best-effort drafts
--     from sector knowledge (refine when real samples arrive)
--
-- Updates the active template per vertical. Run once in Supabase.
-- Safe to re-run (idempotent: overwrites field_schema by vertical).
-- ============================================================

update reference_templates
   set field_schema = '{"sector_note": "Care reference — designed from real CQC-sector samples (Little Angels, Fysc, Reliance, Britmedicare, For You Social Care).", "fields": [{"key": "referee_relationship", "label": "Your relationship to the candidate / capacity in which you knew them", "type": "text"}, {"key": "known_from", "label": "Dates employed / known from", "type": "text"}, {"key": "known_to", "label": "Dates employed / known to", "type": "text"}, {"key": "candidate_job_title", "label": "Candidate''s job title during employment", "type": "text"}, {"key": "reason_for_leaving", "label": "Reason for leaving", "type": "text"}, {"key": "conduct", "label": "General conduct", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "timekeeping", "label": "Timekeeping / punctuality", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "reliability", "label": "Reliability / attendance", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "communication", "label": "Communication skills", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "colleagues", "label": "Relationship with colleagues", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "service_users", "label": "Relationship with service users / people they support", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "integrity", "label": "Honesty & integrity", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "quality", "label": "Quality of work", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "safeguarding_issues", "label": "Were there any safeguarding, misconduct or disciplinary issues during their employment?", "type": "yesno"}, {"key": "safeguarding_details", "label": "If yes, please give details", "type": "textarea"}, {"key": "would_reemploy", "label": "Would you re-employ this person?", "type": "yesno"}, {"key": "suitable_vulnerable_adults", "label": "Do you consider them suitable to work with vulnerable adults?", "type": "yesno"}, {"key": "character", "label": "Brief description of their character and conduct", "type": "textarea"}, {"key": "additional_comments", "label": "Additional comments", "type": "textarea"}, {"key": "declaration", "label": "I declare this reference is true and accurate to the best of my knowledge", "type": "boolean"}], "required": ["safeguarding_issues", "would_reemploy", "suitable_vulnerable_adults", "declaration"]}'::jsonb
 where vertical = 'care'::vertical_t and is_active = true;

update reference_templates
   set field_schema = '{"sector_note": "Healthcare reference (NMC & HCPC) — DRAFT from sector knowledge; refine when real NHS samples are available.", "fields": [{"key": "referee_relationship", "label": "Your professional relationship to the candidate", "type": "text"}, {"key": "known_from", "label": "Dates employed / known from", "type": "text"}, {"key": "known_to", "label": "Dates employed / known to", "type": "text"}, {"key": "candidate_job_title", "label": "Candidate''s role / banding during employment", "type": "text"}, {"key": "reason_for_leaving", "label": "Reason for leaving", "type": "text"}, {"key": "registration_number", "label": "Candidate''s NMC / HCPC registration number (if known)", "type": "text"}, {"key": "clinical_competence", "label": "Clinical competence", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "conduct", "label": "Professional conduct", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "timekeeping", "label": "Timekeeping / attendance", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "communication", "label": "Communication with patients & colleagues", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "teamwork", "label": "Teamwork", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "record_keeping", "label": "Record keeping & documentation", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "integrity", "label": "Honesty & integrity", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "fitness_concerns", "label": "Were there any fitness-to-practise, conduct or capability concerns?", "type": "yesno"}, {"key": "fitness_details", "label": "If yes, please give details", "type": "textarea"}, {"key": "safeguarding_issues", "label": "Any safeguarding concerns regarding patients or vulnerable people?", "type": "yesno"}, {"key": "safeguarding_details", "label": "If yes, please give details", "type": "textarea"}, {"key": "would_reemploy", "label": "Would you re-employ this person?", "type": "yesno"}, {"key": "suitable_role", "label": "Do you consider them suitable for the role applied for?", "type": "yesno"}, {"key": "additional_comments", "label": "Additional comments", "type": "textarea"}, {"key": "declaration", "label": "I declare this reference is true and accurate to the best of my knowledge", "type": "boolean"}], "required": ["fitness_concerns", "safeguarding_issues", "would_reemploy", "suitable_role", "declaration"]}'::jsonb
 where vertical = 'healthcare'::vertical_t and is_active = true;

update reference_templates
   set field_schema = '{"sector_note": "Education reference (KCSIE safer recruitment) — DRAFT from sector knowledge; refine when real school samples are available.", "fields": [{"key": "referee_relationship", "label": "Your relationship to the candidate (e.g. headteacher, line manager)", "type": "text"}, {"key": "known_from", "label": "Dates employed / known from", "type": "text"}, {"key": "known_to", "label": "Dates employed / known to", "type": "text"}, {"key": "candidate_job_title", "label": "Candidate''s role during employment", "type": "text"}, {"key": "reason_for_leaving", "label": "Reason for leaving", "type": "text"}, {"key": "conduct", "label": "Professional conduct", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "teaching_ability", "label": "Teaching / role effectiveness", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "timekeeping", "label": "Timekeeping / attendance", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "communication", "label": "Communication", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "pupil_relationships", "label": "Relationships with pupils / young people", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "colleagues", "label": "Relationships with colleagues", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "integrity", "label": "Honesty & integrity", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "disciplinary_issues", "label": "Were there any disciplinary or capability proceedings?", "type": "yesno"}, {"key": "disciplinary_details", "label": "If yes, please give details", "type": "textarea"}, {"key": "safeguarding_issues", "label": "Have any safeguarding or child-protection concerns ever been raised about this person? (KCSIE)", "type": "yesno"}, {"key": "safeguarding_details", "label": "If yes, please give details", "type": "textarea"}, {"key": "suitable_children", "label": "Do you consider this person suitable to work with children?", "type": "yesno"}, {"key": "would_reemploy", "label": "Would you re-employ this person?", "type": "yesno"}, {"key": "additional_comments", "label": "Additional comments", "type": "textarea"}, {"key": "declaration", "label": "I declare this reference is true and accurate to the best of my knowledge", "type": "boolean"}], "required": ["disciplinary_issues", "safeguarding_issues", "suitable_children", "would_reemploy", "declaration"]}'::jsonb
 where vertical = 'teaching'::vertical_t and is_active = true;

update reference_templates
   set field_schema = '{"sector_note": "Practice-based social work reference (PCF / KSS) — DRAFT from sector knowledge; refine when real samples are available.", "fields": [{"key": "referee_relationship", "label": "Your relationship to the candidate (e.g. practice supervisor)", "type": "text"}, {"key": "known_from", "label": "Dates employed / known from", "type": "text"}, {"key": "known_to", "label": "Dates employed / known to", "type": "text"}, {"key": "candidate_job_title", "label": "Candidate''s role during employment", "type": "text"}, {"key": "reason_for_leaving", "label": "Reason for leaving", "type": "text"}, {"key": "registration_number", "label": "Social Work England registration number (if known)", "type": "text"}, {"key": "practice_competence", "label": "Practice competence (PCF/KSS)", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "conduct", "label": "Professional conduct", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "timekeeping", "label": "Timekeeping / attendance", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "communication", "label": "Communication & recording", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "service_users", "label": "Relationships with people who use services", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "integrity", "label": "Honesty & integrity", "type": "select", "options": ["Excellent", "Good", "Satisfactory", "Poor"]}, {"key": "conduct_concerns", "label": "Were there any conduct, capability or fitness-to-practise concerns?", "type": "yesno"}, {"key": "conduct_details", "label": "If yes, please give details", "type": "textarea"}, {"key": "safeguarding_issues", "label": "Any safeguarding concerns regarding adults or children?", "type": "yesno"}, {"key": "safeguarding_details", "label": "If yes, please give details", "type": "textarea"}, {"key": "would_reemploy", "label": "Would you re-employ this person?", "type": "yesno"}, {"key": "suitable_role", "label": "Do you consider them suitable for the role applied for?", "type": "yesno"}, {"key": "additional_comments", "label": "Additional comments", "type": "textarea"}, {"key": "declaration", "label": "I declare this reference is true and accurate to the best of my knowledge", "type": "boolean"}], "required": ["conduct_concerns", "safeguarding_issues", "would_reemploy", "suitable_role", "declaration"]}'::jsonb
 where vertical = 'social_work'::vertical_t and is_active = true;

-- Verify:
-- select vertical, jsonb_array_length(field_schema->'fields') as fields,
--        jsonb_array_length(field_schema->'required') as required
-- from reference_templates where is_active = true order by vertical;
